#!/bin/bash
ssh root@srv "bash -c \"rm /var/lib/apt/lists/lock; rm /var/lib/dpkg/lock; rm /var/lib/dpkg/lock-frontend; rm /var/cache/apt/archives/lock; rm /var/lib/dpkg/updates/0001; dpkg --configure -a\""
ssh root@node1 "bash -c \"rm /var/lib/apt/lists/lock; rm /var/lib/dpkg/lock; rm /var/lib/dpkg/lock-frontend; rm /var/cache/apt/archives/lock; rm /var/lib/dpkg/updates/0001; dpkg --configure -a\""
ssh root@node2 "bash -c \"rm /var/lib/apt/lists/lock; rm /var/lib/dpkg/lock; rm /var/lib/dpkg/lock-frontend; rm /var/cache/apt/archives/lock; rm /var/lib/dpkg/updates/0001; dpkg --configure -a\""
ssh root@node3 "bash -c \"rm /var/lib/apt/lists/lock; rm /var/lib/dpkg/lock; rm /var/lib/dpkg/lock-frontend; rm /var/cache/apt/archives/lock; rm /var/lib/dpkg/updates/0001; dpkg --configure -a\""

